name = "OptMethods"
uuid = "550e4208-90ba-559c-a997-847ba616543e"
authors = ["Le Nhut NAm <nam.lnhut@gmail.com>"]
version = "0.1.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
julia = "1.6"
SpecialFunctions = "2"